### ISSUE TITLE
Menampilkan produk berdasarkan brands

### ISSUE THREAD

**Issue by rizky201008** [nurfaizfy/digiflazz-php-library#1]
@nurfaizfy Bagaimana caranya supaya saya bisa menampilkan berdasarkan brand pada resposnse getPrepaid seperti halnya saya ingin menampilkan suatu produk namun produk yang ingin saya tampilkan hanya berupa peroduk yang mempunyai brand Telkosmel saja semoga dibalas :) 🙏

**Comment by hendriksinaga13** [comment]
parsing data dengan tanda gini kak "->ambil atribute" baru ambil
